// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exbnrehtwouvztlmofif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4Ym5yZWh0d291dnp0bG1vZmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjEyNDAsImV4cCI6MjA2MDAzNzI0MH0.MZuO7kX1Hw6euiGMQEr33-ESaReBGK50FXZl93sgHpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);